"""add permissions, forced password change, employee email

Revision ID: b57e91bdf25b
Revises: bb23b78c5ad3
Create Date: 2026-09-17 10:32:07.666753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57e91bdf25b'
down_revision = 'bb23b78c5ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('permissions')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
